apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connection-service
  name: udaconnect-connection-service
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30040
  selector:
    service: udaconnect-connection-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connection-service
  name: udaconnect-connection-services
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connection-service
  template:
    metadata:
      labels:
        service: udaconnect-connection-service
    spec:
      containers:
        - image: suchan03/udaconnect-connection-service:latest
          name: person
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
      restartPolicy: Always
